### ISSUE TITLE
about the GAN loss

### ISSUE THREAD

**Issue by lz666win** [sefibk/KernelGAN#15]
Nice work! I try my own data, but there is the problem:
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    main()
  File "train.py", line 36, in main
    train(conf)
  File "train.py", line 16, in train
    gan.train(g_in, d_in)
  File "F:\lz666\KernelGAN-master\kernelGAN.py", line 67, in train
    self.train_g()
  File "F:\lz666\KernelGAN-master\kernelGAN.py", line 82, in train_g
    loss_g = self.criterionGAN(d_last_layer=d_pred_fake, is_d_input_real=True)
  File "F:\lz666\KernelGAN-master\loss.py", line 26, in forward
    return self.loss(d_last_layer, label_tensor)
  File "E:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\anaconda\lib\site-packages\torch\nn\modules\loss.py", line 87, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "E:\anaconda\lib\site-packages\torch\nn\functional.py", line 1700, in l1_loss
    reduction = _Reduction.get_enum(reduction)
  File "E:\anaconda\lib\site-packages\torch\nn\functional.py", line 30, in get_enum
    raise ValueError(reduction + " is not a valid value for reduction")
ValueError: mean is not a valid value for reduction

I do not know much about GAN, my data is a 192*192 png file.

**Comment by sefibk** [comment]
Please verify the packages from the requirements.txt
